### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by Talento90** [heremaps/examples#10]
Hey guys could you please upgrade your scrips to be compatible with API v7.2? Currently all the examples are using version 6.2 that does not work anymore!

Thanks!

**Comment by freethan** [comment]
Hi @Talento90 , the examples included in this repository make use of the 2.5.x version of the HERE JavaScript API for maps which is superseded by version 3.x. The 2.5.x version is using the old Routing API (6.2) .

Please take a look at https://github.com/heremaps/maps-api-for-javascript-examples for an updated list of examples, using the version 3.x of the JavaScript API.

We'll make sure to point others that way in the README file in case they want to be using the latest JS api. Thanks for the feedback :)

**Comment by Talento90** [comment]
Thanks a lot!!! 👍 👍 👍
