### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by liiuzhenzhou11** [heremaps/examples#5]
hi,
I have a question to ask you to help .
Under IE8 browser,I use API [nokia.maps.map.provider.ImageProvider] memory leak occurs when the image is superimposed on the map.

*Repeated operation of the following steps（Size of the picture in 300KB）
1 . dividedBerlin = new nokia.maps.map.provider.ImageProvider({
min: 0,
max: 30,
getBoundingBox: function () {
return imageBounds;
},
getUrl: function () {
return imgSrc;
}
});
map.overlays.add(dividedBerlin);

2 . clear 

map.overlays.remove(dividedBerlin);
dividedBerlin = null;

**Comment by freethan** [comment]
No updates to this issue since 2014, closing.
