### ISSUE TITLE
i want to display boundary by postal code

### ISSUE THREAD

**Issue by Mr-Luo** [heremaps/examples#9]
hello,i want to display boundary by postal code,which api can i use?I could't found it

**Comment by freethan** [comment]
Hi, if I understood your request correctly, under the Maps API for JavaScript 2.5 it would require you:

1. to query the Geocoding API's Reverse Geocode endpoint (https://developer.here.com/rest-apis/documentation/geocoder/topics/resource-reverse-geocode.html) with the appropriate parameters (level & additionaldata=IncludeShapeLevel) and retrieve a postal code's WKT shape
2. convert the WKT shape into a Polygon shape (https://developer.here.com/documentation/download/maps_js_pub/2.5.4/Maps%20API%20for%20JavaScript%20Public%20v2.5.4%20Developer's%20Guide.pdf#page=458&zoom=auto,81.692,142.836)
3. add the shape to the map container

Here is an example that makes use of a WKT parser to add postal code shapes on the map (select postalCode on the dropdown): http://heremaps.github.io/examples/explorer.html#wkt-parser__region-shape-on-click

Source code is here: https://github.com/heremaps/examples/blob/master/maps_api_for_javascript/demos/wkt-parser/region-shape-on-click.html

**Comment by Mr-Luo** [comment]
thanks very much,I will to do that.

**Comment by freethan** [comment]
Hi again,
I will then close this issue. Cheers.
